### ISSUE TITLE
minimumInputLength = 0 filter issue

### ISSUE THREAD

**Issue by BioSin** [Innqube/ng2-iq-select2#11]
As I see in documentation and source code:
@Input() minimumInputLength: if this value is '0', only makes one request to server and later filter values on client side, works as a dropDown in single mode. Functionality for values bigger than 0 not implemented yet.

When we use minimumInputLength = 0 you implemented you own filter function, BUT for instance I have in my local observable 500 elements. In this case your component tries to render all 500 items, and when I click on select there are delay for ~1 second, maybe will be useful to add limit(optional) `@Input()`, to avoid the delay. Also may be useful to add trackBy for *ngFor results, to accelerate it.

**Comment by diegofsza** [comment]
I don't see a clear way to optimize this. I don't believe I know too much ng2 yet to optimize it. If you have code suggestions I will happily integrate a pull request.

In any case, I think the programmer should take a care of how many results will be loaded at a maximum. I will add a feature soon, to load a batch of results and indicate with a message if there are more results available, so that the user knows he should write more characters to narrow the result list. This will require the limit you are talking about.
I will also add the default minimumInputLength behavior.
