### ISSUE TITLE
When clientMode is set to false why search is not working ?

### ISSUE THREAD

**Issue by rpetrovic** [Innqube/ng2-iq-select2#36]
I have dynamically loaded data to  'dataSourceProvider' and i must use [clientMode]="false" but then search is not working anymore...

I think it is not the big problem to implement this feature and one way to do this is like this.

We must change just two lines of code in private functions 'fetchData' and adaptItems.

Original code:
```javascript 
private fetchData(term: string): Observable<IqSelect2Item[]> {
	return this
	    .dataSourceProvider(term)
	    .map((items: T[]) => this.adaptItems(items));
}

private adaptItems(items: T[]): IqSelect2Item[] {
	let convertedItems = [];
	items.map((item) => this.iqSelect2ItemAdapter(item))
	    .forEach((iqSelect2Item) => convertedItems.push(iqSelect2Item))
	return convertedItems;
}
```

Changed: 

```javascript 
private fetchData(term: string): Observable<IqSelect2Item[]> {
	return this
	    .dataSourceProvider(term)
	    .map((items: T[]) => this.adaptItems(items, term))
}

private adaptItems(items: T[], term: string): IqSelect2Item[] {
	let convertedItems = [];
	items.map((item) => this.iqSelect2ItemAdapter(item))
	    .filter((iqSelect2Item) => !this.alreadySelected(iqSelect2Item) && (term !== '' ? this.containsText(iqSelect2Item, term) : true))
	    .forEach((iqSelect2Item) => convertedItems.push(iqSelect2Item))
	return convertedItems;
}
```

**Comment by diegofsza** [comment]
The component was originally made to make the filtering remotely, so that you can choose a value from a large list without the need to bring the whole list to the client, avoiding big data transfers and large volume of values being handled on the client. That's the reason why it won't filter the values for you if it isn't working client-side. It expects the remote end to have done this for you.

Just to be sure the functionality is clear: why must you use `[clientMode]="false"`? Even though you use the `[clientMode]="true"`, the component will fetch the data remotely once, and then filter it on the browser. Wouldn't something like what was mentioned on #30, help in your case?

**Comment by rpetrovic** [comment]
The reason why I must use  [clientMode]="false" it's due to fetching of remote data more times not just once. 

I didn't realize that I can use this code line

```javascript
     this.firstObservable = () => Observable.of(this.firstDropdown)
```

like this

```javascript
    containsText(item: any, term: string) {
        return item.caption.toUpperCase().indexOf(term.toUpperCase()) !== -1;
    }

    this.firstObservable = (term: string) => Observable.of(this.firstDropdown.filter( (item) => containsText(item, term))); 
```

Thank You for your quick response, You have directed me to the accurate reference, so I managed to solve the problem using the code from second section.
